#!/usr/bin/env node
// Fetches selected DB2 CSV dumps from wago.tools and emits Lua lookup
// tables under addon/Aftertale/Data/. Re-run when a new patch
// drops to refresh names: `npm run db2:bake`.
//
// Why this exists: in-game enrichment can miss data (older captures,
// the simulator, server hiccups). Baking authoritative names from
// Blizzard's own DB2 tables means the Chronicle never has to fall back
// to "Unknown Lands" or generic placeholders -- if Blizzard knows the
// name, we know it too.
//
// Quest titles are intentionally NOT baked: they aren't shipped in
// modern DB2 dumps (server-resolved). Quest fallback uses
// C_QuestLog.GetTitleForQuestID at runtime instead.

import { writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR  = resolve(__dirname, "..", "addon", "Aftertale", "Data");

// table => { idCol, nameCol, varName, header }
const TABLES = {
  UiMap: {
    idCol:   "ID",
    nameCol: "Name_lang",
    varName: "UiMap",
    header:  "Zone / sub-zone names keyed by UiMapID. Used to humanize\n-- ZONE_CHANGED_NEW_AREA and any other event carrying a uiMapID."
  },
  Achievement: {
    idCol:   "ID",
    nameCol: "Title_lang",
    varName: "Achievement",
    header:  "Achievement titles keyed by AchievementID. Used as the\n-- fallback when ACHIEVEMENT_EARNED enrichment is missing."
  }
};

// Tiny CSV parser that handles "quoted, with commas" cells. wago.tools
// CSVs are well-formed (quotes are doubled to escape) so we can keep
// this dead simple instead of pulling in a dependency.
function* parseCSV(text) {
  let i = 0, field = "", row = [], inQuotes = false;
  while (i < text.length) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQuotes = false; i++; continue;
      }
      field += c; i++; continue;
    }
    if (c === '"') { inQuotes = true; i++; continue; }
    if (c === ",") { row.push(field); field = ""; i++; continue; }
    if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.length > 1 || row[0] !== "") yield row;
      row = []; i++; continue;
    }
    field += c; i++;
  }
  if (field.length || row.length) { row.push(field); yield row; }
}

function luaEscape(s) {
  if (s.includes("]]") || /[\r\n]/.test(s)) {
    return "[==[" + s + "]==]";
  }
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\t/g, "\\t") + '"';
}

async function bakeTable(name, cfg) {
  const url = `https://wago.tools/db2/${name}/csv`;
  process.stdout.write(`fetching ${name}... `);
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const csv = await res.text();
  console.log(`${(csv.length / 1024).toFixed(1)}KB`);

  const rows = parseCSV(csv);
  const header = rows.next().value;
  const idIdx   = header.indexOf(cfg.idCol);
  const nameIdx = header.indexOf(cfg.nameCol);
  if (idIdx < 0 || nameIdx < 0) {
    throw new Error(`${name}: missing required columns (${cfg.idCol}, ${cfg.nameCol}) in [${header.join(", ")}]`);
  }

  const entries = [];
  for (const row of rows) {
    const id   = row[idIdx];
    const text = row[nameIdx];
    if (!id || !text) continue;
    const n = Number(id);
    if (!Number.isFinite(n)) continue;
    entries.push([n, text]);
  }
  entries.sort((a, b) => a[0] - b[0]);

  const lines = [];
  lines.push("-- AUTO-GENERATED by tools/fetch-db2.mjs -- do not edit by hand.");
  lines.push(`-- Source: https://wago.tools/db2/${name}/csv`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- ${cfg.header.replace(/\n/g, "\n-- ")}`);
  lines.push("");
  lines.push("local _, NS = ...");
  lines.push("NS.DB2 = NS.DB2 or {}");
  lines.push(`NS.DB2.${cfg.varName} = {`);
  for (const [id, text] of entries) {
    lines.push(`  [${id}] = ${luaEscape(text)},`);
  }
  lines.push("}");
  lines.push("");

  const outPath = resolve(DATA_DIR, `DB2_${cfg.varName}.lua`);
  await writeFile(outPath, lines.join("\n"), "utf8");
  console.log(`  wrote ${entries.length} entries -> ${outPath}`);
  return { name, count: entries.length, path: outPath };
}

async function main() {
  await mkdir(DATA_DIR, { recursive: true });
  const results = [];
  for (const [name, cfg] of Object.entries(TABLES)) {
    results.push(await bakeTable(name, cfg));
  }
  console.log("\nDone:");
  for (const r of results) console.log(`  ${r.name}: ${r.count} entries`);
}

main().catch(err => {
  console.error("fetch-db2 failed:", err);
  process.exit(1);
});
